version: 2.1

jobs:
  format:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.5.0 python3 -
      - run: poetry install --no-ansi
      - run: poetry run black --check --diff .
  lint:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.5.0 python3 -
      - run: poetry install --no-ansi
      - run: poetry run flake8 src/
  test:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.5.0 python3 -
      - run: poetry install -vvv --with test --no-ansi
      - run: poetry run pytest

workflows:
  version: 2
  main:
    jobs:
      - format
      - lint
      - test